### PR TITLE
Fix link+valid HTML.

### PR DESCRIPTION
**Pull request by shlomif**
I hereby put my changes under CC0/PD but this repo should really have a LICENSE
file.

### CODE REVIEW

**Comment by szabgab** [comment]
The repo now has a license file. Do you still wish to contribute?

**Comment by shlomif** [comment]
@szabgab : yes I do. my changes remain under CC0.

**Comment by szabgab** [comment]
But as I see you remove one of the links instead of fixing it. Please fix the link.

**Comment by shlomif** [comment]
On Tue, 05 Dec 2017 05:00:56 -0800
Gabor Szabo <notifications@github.com> wrote:

> But as I see you remove one of the links instead of fixing it. Please fix the
> link.
> 

Done, thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Apple Inc. is Evil - http://www.shlomifish.org/open-source/anti/apple/

It is impossible to make anything foolproof because fools are so ingenious.
    — Source Unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by szabgab** [comment]
thanks

**Comment by shlomif** [comment]
On Tue, 05 Dec 2017 17:28:45 +0000 (UTC)
Gabor Szabo <notifications@github.com> wrote:

> thanks
> 

thanks - and you are welcome.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Understand what Open Source is - http://shlom.in/oss-fs

After all is said and done, a hell of a lot more is said than done.
    — Unclear source, via fortune-mod.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request merged**
